### ISSUE TITLE
output_iterator Definition

### ISSUE THREAD

**Issue by mgcsysinfcat** [arturbac/small_vectors#3]
The concept checks if the iterator can be converted to std::input_iterator_tag, but the name of the concept is concept_output_iterator. This seems to be contradictory.
 I would expect an output iterator concept to check against std::output_iterator_tag.Could you please clarify if these are intentional or if they're mistakes? Thanks in advance for your help.

https://github.com/arturbac/small_vectors/blob/5ccbda39de5a815e978086f0fe9b53b0d51085ae/include/coll/detail/coll_concepts.h#L24

**Comment by arturbac** [comment]
It was intentional as for output iterator You can not determine output  expected type as it is just required to accept _anything_ that will be convertible to value type in it operator(value_type ).
There are a lot of checks if source type matches output type in this code.
Wonder/Need to reevaluate this if I can do it better (c++23/c++26) output iterator concept with restricted to some type..

**Comment by mgcsysinfcat** [comment]
Thanks for the clarification.
